apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "logscale-strimzi-kafka.fullname" . }}-extra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: strimzi-kafka-broker
subjects:
- kind: ServiceAccount
  name: {{ include "logscale-strimzi-kafka.fullname" . }}-kafka
  namespace: {{ .Release.Namespace }}
