apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "logscale-strimzi-kafka.fullname" . }}
  labels:
    {{- include "logscale-strimzi-kafka.labels" . | nindent 4 }}
spec:
spec:
  cruiseControl: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    template:
      pod:
        {{- with .Values.kafka.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
    resources:
      {{- toYaml .Values.kafka.resources | nindent 6 }}    
    config:
      auto.create.topics.enable: {{- with .Values.kafka.allowAutoCreate | default "false" | quote }}
      default.replication.factor: 2
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.facto: 2
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
        authentication:
          type: tls

    replicas: {{ .Values.kafka.replicas }}
    storage:
      {{- toYaml .Values.kafka.storage | nindent 6 }}    

  zookeeper:
    template:
      pod:
        {{- with .Values.zookeeper.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}  
    resources:
      {{- toYaml .Values.zookeeper.resources | nindent 6 }}    
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      {{- toYaml .Values.zookeeper.storage | nindent 6 }}    
