apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaRebalance
metadata:
  name: {{ include "logscale-strimzi-kafka.fullname" . }}
  labels:
    strimzi.io/cluster: {{ include "logscale-strimzi-kafka.fullname" . }}
spec: {}