apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: {{ include "logscale-strimzi-kafka.fullname" . }}
  labels:
    strimzi.io/cluster: {{ include "logscale-strimzi-kafka.fullname" . }}
spec: 
  goals:
    - NetworkInboundCapacityGoal
    - DiskCapacityGoal
    - RackAwareGoal
    - NetworkOutboundCapacityGoal
    - CpuCapacityGoal
    - ReplicaCapacityGoal